# Generated by Django 5.0.7 on 2024-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('numeroRicetta', models.IntegerField()),
                ('ingrediente', models.CharField(max_length=200)),
                ('quantita', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codISBN', models.CharField(max_length=13, unique=True)),
                ('titolo', models.CharField(max_length=200)),
                ('anno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPagina', models.IntegerField()),
                ('libro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RicettaPubblicata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroRicetta', models.IntegerField()),
                ('libro', models.IntegerField()),
                ('numeroPagina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RicettaRegionale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('regione', models.IntegerField()),
                ('ricetta', models.IntegerField()),
            ],
            options={
                'unique_together': {('regione', 'ricetta')},
            },
        ),
    ]
