# Generated by Django 5.0.7 on 2024-07-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codISBN', models.CharField(max_length=13, unique=True)),
                ('titolo', models.CharField(max_length=200)),
                ('anno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.IntegerField()),
                ('libro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(max_length=200)),
                ('quantita', models.IntegerField()),
                ('numeroRicetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienti', to='data_service.ricetta')),
            ],
        ),
        migrations.CreateModel(
            name='RicettaPubblicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.libro')),
                ('numeroPagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.pagina')),
                ('numeroRicetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.ricetta')),
            ],
        ),
        migrations.CreateModel(
            name='RicettaRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.regione')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_service.ricetta')),
            ],
            options={
                'unique_together': {('regione', 'ricetta')},
            },
        ),
    ]
