# Generated by Django 5.0.7 on 2024-07-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingrediente',
            unique_together={('numero', 'numeroRicetta')},
        ),
    ]
